services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_sales_agent
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Almaty
      - TZ=Asia/Almaty
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - n8n_data:/home/node/.n8n

  rag:
    build: ./rag
    container_name: rag_service
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=llama-3.3-70b-versatile
    volumes:
      - ./rag/data:/app/data

volumes:
  n8n_data:
